const FIVF = [
  { label: '平均获卵数', value: 'pjhls', dataType: 'normal' },
  { label: '2PN受精率', value: 'pn2sjl', dataType: 'percent' },
  { label: '优质胚胎率', value: 'yzptl', dataType: 'percent' },
  { label: '取消率', value: 'qxl', dataType: 'percent' },
  { label: '无可移植胚胎周期率', value: 'wkyzptzql', dataType: 'percent' },
  { label: '全胚冷冻率', value: 'qpldl', dataType: 'percent' },
  { label: '移植率', value: 'yzl', dataType: 'percent' },
  { label: '种植率', value: 'zzl', dataType: 'percent' },
  { label: '平均移植胚胎数', value: 'pjyzpts', dataType: 'normal' },
  { label: '临床妊娠率', value: 'lcrsl', dataType: 'percent' },
  { label: '多胎妊娠率', value: 'dtrsl', dataType: 'percent' },
  { label: '宫外孕发生率', value: 'gwyfsl', dataType: 'percent' },
  { label: '流产率', value: 'zqlcl', dataType: 'percent' },
  { label: '活产率', value: 'hcl', dataType: 'percent' },
  { label: '分娩率', value: 'fml', dataType: 'percent' },
  { label: '出生男女比例', value: 'csnnbl', dataType: 'percent' },
  { label: '出生缺陷种类占比', value: 'csqxzlzb', dataType: 'percent' },
  { label: '出生缺陷发生率', value: 'csqxfsl', dataType: 'percent' },
];
const FICSI = [
  { label: '平均获卵数', value: 'pjhls', dataType: 'normal' },
  { label: 'MII率', value: 'mlllv', dataType: 'percent' },
  { label: '2PN受精率', value: 'pn2sjl', dataType: 'percent' },
  { label: '优质胚胎率', value: 'yzptl', dataType: 'percent' },
  { label: '取消率', value: 'qxl', dataType: 'percent' },
  { label: '无可移植胚胎周期率', value: 'wkyzptzql', dataType: 'percent' },
  { label: '全胚冷冻率', value: 'qpldl', dataType: 'percent' },
  { label: '移植率', value: 'yzl', dataType: 'percent' },
  { label: '种植率', value: 'zzl', dataType: 'percent' },
  { label: '平均移植胚胎数', value: 'pjyzpts', dataType: 'normal' },
  { label: '临床妊娠率', value: 'lcrsl', dataType: 'percent' },
  { label: '多胎妊娠率', value: 'dtrsl', dataType: 'percent' },
  { label: '宫外孕发生率', value: 'gwyfsl', dataType: 'percent' },
  { label: '流产率', value: 'zqlcl', dataType: 'percent' },
  { label: '活产率', value: 'hcl', dataType: 'percent' },
  { label: '分娩率', value: 'fml', dataType: 'percent' },
  { label: '出生男女比例', value: 'csnnbl', dataType: 'percent' },
  { label: '出生缺陷种类占比', value: 'csqxzlzb', dataType: 'percent' },
  { label: '出生缺陷发生率', value: 'csqxfsl', dataType: 'percent' },
];

const FIVFICSI = [
  { label: '平均获卵数', value: 'pjhls', dataType: 'normal' },
  { label: '2PN受精率', value: 'pn2sjl', dataType: 'percent' },
  { label: '优质胚胎率', value: 'yzptl', dataType: 'percent' },
  { label: '取消率', value: 'qxl', dataType: 'percent' },
  { label: '无可移植胚胎周期率', value: 'wkyzptzql', dataType: 'percent' },
  { label: '全胚冷冻率', value: 'qpldl', dataType: 'percent' },
  { label: '移植率', value: 'yzl', dataType: 'percent' },
  { label: '种植率', value: 'zzl', dataType: 'percent' },
  { label: '平均移植胚胎数', value: 'pjyzpts', dataType: 'normal' },
  { label: '临床妊娠率', value: 'lcrsl', dataType: 'percent' },
  { label: '多胎妊娠率', value: 'dtrsl', dataType: 'percent' },
  { label: '宫外孕发生率', value: 'gwyfsl', dataType: 'percent' },
  { label: '流产率', value: 'zqlcl', dataType: 'percent' },
  { label: '活产率', value: 'hcl', dataType: 'percent' },
  { label: '分娩率', value: 'fml', dataType: 'percent' },
  { label: '出生男女比例', value: 'csnnbl', dataType: 'percent' },
  { label: '出生缺陷种类占比', value: 'csqxzlzb', dataType: 'percent' },
  { label: '出生缺陷发生率', value: 'csqxfsl', dataType: 'percent' },
];

const GIVF = [
  { label: '平均获卵数', value: 'pjhls', dataType: 'normal' },
  { label: '2PN受精率', value: 'pn2sjl', dataType: 'percent' },
  { label: '优质胚胎率', value: 'yzptl', dataType: 'percent' },
  { label: '取消率', value: 'qxl', dataType: 'percent' },
  { label: '无可移植胚胎周期率', value: 'wkyzptzql', dataType: 'percent' },
  { label: '全胚冷冻率', value: 'qpldl', dataType: 'percent' },
  { label: '移植率', value: 'yzl', dataType: 'percent' },
  { label: '种植率', value: 'zzl', dataType: 'percent' },
  { label: '平均移植胚胎数', value: 'pjyzpts', dataType: 'normal' },
  { label: '临床妊娠率', value: 'lcrsl', dataType: 'percent' },
  { label: '多胎妊娠率', value: 'dtrsl', dataType: 'percent' },
  { label: '宫外孕发生率', value: 'gwyfsl', dataType: 'percent' },
  { label: '流产率', value: 'zqlcl', dataType: 'percent' },
  { label: '活产率', value: 'hcl', dataType: 'percent' },
  { label: '分娩率', value: 'fml', dataType: 'percent' },
  { label: '出生男女比例', value: 'csnnbl', dataType: 'percent' },
  { label: '出生缺陷种类占比', value: 'csqxzlzb', dataType: 'percent' },
  { label: '出生缺陷发生率', value: 'csqxfsl', dataType: 'percent' },
];

const FET = [
  { label: '胚胎复苏率', value: 'ptfsl', dataType: 'percent' },
  { label: '平均移植胚胎数', value: 'pjyzpts', dataType: 'normal' },
  { label: '种植率', value: 'zzl', dataType: 'percent' },
  { label: '临床妊娠率', value: 'lcrsl', dataType: 'percent' },
  { label: '多胎妊娠率', value: 'dtrsl', dataType: 'percent' },
  { label: '宫外孕发生率', value: 'gwyfsl', dataType: 'percent' },
  { label: '流产率', value: 'zqlcl', dataType: 'percent' },
  { label: '活产率', value: 'hcl', dataType: 'percent' },
  { label: '分娩率', value: 'fml', dataType: 'percent' },
  { label: '出生缺陷种类占比', value: 'csqxzlzb', dataType: 'percent' },
  { label: '出生缺陷发生率', value: 'csqxfsl', dataType: 'percent' },
];

const PGTA = [
  { label: '平均获卵数', value: 'pjhls', dataType: 'normal' },
  { label: '2PN受精率', value: 'pn2sjl', dataType: 'percent' },
  { label: '卵裂率', value: 'lll', dataType: 'percent' },
  { label: '活检胚胎率', value: 'hjptl', dataType: 'percent' },
  { label: '可移植胚胎率', value: 'kyzptl', dataType: 'percent' },
  { label: '平均移植胚胎数', value: 'pjyzpts', dataType: 'normal' },
  { label: '种植率', value: 'zzl', dataType: 'percent' },
  { label: '临床妊娠率', value: 'lcrsl', dataType: 'percent' },
  { label: '多胎妊娠率', value: 'dtrsl', dataType: 'percent' },
  { label: '羊穿比例', value: 'ycbl', dataType: 'percent' },
  { label: '宫外孕发生率', value: 'gwyfsl', dataType: 'percent' },
  { label: '流产率', value: 'zqlcl', dataType: 'percent' },
  { label: '活产率', value: 'hcl', dataType: 'percent' },
  { label: '分娩率', value: 'fml', dataType: 'percent' },
  { label: '羊穿结果与胚胎检测结果一致率', value: 'ycjgyptjcjgyzl', dataType: 'percent' },
  { label: '出生缺陷种类占比', value: 'csqxzlzb', dataType: 'percent' },
  { label: '出生缺陷发生率', value: 'csqxfsl', dataType: 'percent' },
];


const PGTSR = [
  { label: '平均获卵数', value: 'pjhls', dataType: 'normal' },
  { label: '2PN受精率', value: 'pn2sjl', dataType: 'percent' },
  { label: '卵裂率', value: 'lll', dataType: 'percent' },
  { label: '活检胚胎率', value: 'hjptl', dataType: 'percent' },
  { label: '可移植胚胎率', value: 'kyzptl', dataType: 'percent' },
  { label: '平均移植胚胎数', value: 'pjyzpts', dataType: 'normal' },
  { label: '种植率', value: 'zzl', dataType: 'percent' },
  { label: '临床妊娠率', value: 'lcrsl', dataType: 'percent' },
  { label: '多胎妊娠率', value: 'dtrsl', dataType: 'percent' },
  { label: '羊穿比例', value: 'ycbl', dataType: 'percent' },
  { label: '宫外孕发生率', value: 'gwyfsl', dataType: 'percent' },
  { label: '流产率', value: 'zqlcl', dataType: 'percent' },
  { label: '活产率', value: 'hcl', dataType: 'percent' },
  { label: '分娩率', value: 'fml', dataType: 'percent' },
  { label: '羊穿结果与胚胎检测结果一致率', value: 'ycjgyptjcjgyzl', dataType: 'percent' },
  { label: '出生缺陷种类占比', value: 'csqxzlzb', dataType: 'percent' },
  { label: '出生缺陷发生率', value: 'csqxfsl', dataType: 'percent' },
];


const PGTM = [
  { label: '平均获卵数', value: 'pjhls', dataType: 'normal' },
  { label: '2PN受精率', value: 'pn2sjl', dataType: 'percent' },
  { label: '卵裂率', value: 'lll', dataType: 'percent' },
  { label: '活检胚胎率', value: 'hjptl', dataType: 'percent' },
  { label: '可移植胚胎率', value: 'kyzptl', dataType: 'percent' },
  { label: '平均移植胚胎数', value: 'pjyzpts', dataType: 'normal' },
  { label: '种植率', value: 'zzl', dataType: 'percent' },
  { label: '临床妊娠率', value: 'lcrsl', dataType: 'percent' },
  { label: '多胎妊娠率', value: 'dtrsl', dataType: 'percent' },
  { label: '羊穿比例', value: 'ycbl', dataType: 'percent' },
  { label: '宫外孕发生率', value: 'gwyfsl', dataType: 'percent' },
  { label: '流产率', value: 'zqlcl', dataType: 'percent' },
  { label: '活产率', value: 'hcl', dataType: 'percent' },
  { label: '分娩率', value: 'fml', dataType: 'percent' },
  { label: '羊穿结果与胚胎检测结果一致率', value: 'ycjgyptjcjgyzl', dataType: 'percent' },
  { label: '出生缺陷种类占比', value: 'csqxzlzb', dataType: 'percent' },
  { label: '出生缺陷发生率', value: 'csqxfsl', dataType: 'percent' },
];

const AIH = [
  { label: '临床妊娠率', value: 'lcrsl', dataType: 'percent' },
  { label: '多胎妊娠率', value: 'dtrsl', dataType: 'percent' },
  { label: '宫外孕发生率', value: 'gwyfsl', dataType: 'percent' },
  { label: '早期流产率', value: 'zqlcl', dataType: 'percent' },
  { label: '活产率', value: 'hcl', dataType: 'percent' },
  { label: '分娩率', value: 'fml', dataType: 'percent' },
  { label: '出生缺陷种类占比', value: 'csqxzlzb', dataType: 'percent' },
  { label: '出生缺陷发生率', value: 'csqxfsl', dataType: 'percent' },
];

const AID = [
  { label: '临床妊娠率', value: 'lcrsl', dataType: 'percent' },
  { label: '多胎妊娠率', value: 'dtrsl', dataType: 'percent' },
  { label: '宫外孕发生率', value: 'gwyfsl', dataType: 'percent' },
  { label: '早期流产率', value: 'zqlcl', dataType: 'percent' },
  { label: '活产率', value: 'hcl', dataType: 'percent' },
  { label: '分娩率', value: 'fml', dataType: 'percent' },
  { label: '出生缺陷种类占比', value: 'csqxzlzb', dataType: 'percent' },
  { label: '出生缺陷发生率', value: 'csqxfsl', dataType: 'percent' },
];

const ZSL = [
  { label: '平均移植胚胎数', value: 'pjyzpts', dataType: 'normal' },
  { label: '种植率', value: 'zzl', dataType: 'percent' },
  { label: '临床妊娠率', value: 'lcrsl', dataType: 'percent' },
  { label: '多胎妊娠率', value: 'dtrsl', dataType: 'percent' },
  { label: '宫外孕发生率', value: 'gwyfsl', dataType: 'percent' },
  { label: '流产率', value: 'zqlcl', dataType: 'percent' },
  { label: '活产率', value: 'hcl', dataType: 'percent' },
  { label: '分娩率', value: 'fml', dataType: 'percent' },
  { label: '出生缺陷种类占比', value: 'csqxzlzb', dataType: 'percent' },
  { label: '出生缺陷发生率', value: 'csqxfsl', dataType: 'percent' },
];

const DRL = [
  { label: '卵子复苏率', value: 'lzfsl', dataType: 'percent' },
  { label: '2PN受精率', value: 'pn2sjl', dataType: 'percent' },
  { label: '优质胚胎率', value: 'yzptl', dataType: 'percent' },
  { label: '有效胚胎率', value: 'yxptl', dataType: 'percent' },
  { label: '平均移植胚胎数', value: 'pjyzpts', dataType: 'normal' },
  { label: '种植率', value: 'zzl', dataType: 'percent' },
  { label: '临床妊娠率', value: 'lcrsl', dataType: 'percent' },
  { label: '多胎妊娠率', value: 'dtrsl', dataType: 'percent' },
  { label: '宫外孕发生率', value: 'gwyfsl', dataType: 'percent' },
  { label: '流产率', value: 'zqlcl', dataType: 'percent' },
  { label: '活产率', value: 'hcl', dataType: 'percent' },
  { label: '分娩率', value: 'fml', dataType: 'percent' },
  { label: '出生缺陷种类占比', value: 'csqxzlzb', dataType: 'percent' },
  { label: '出生缺陷发生率', value: 'csqxfsl', dataType: 'percent' },
];


const SITUATION_LIST = {
  FuJingIvf: FIVF,
  FuJingIcsi: FICSI,
  FuJingIvfIcsi: FIVFICSI,
  GongJingIvf: GIVF,
  Fet: FET,
  Pgta: PGTA,
  Pgtsr: PGTSR,
  Pgtm: PGTM,
  Aih: AIH,
  Aid: AID,
  ZengShouLuan: ZSL,
  DongRongLuan: DRL,
};

export {
  // eslint-disable-next-line import/prefer-default-export
  SITUATION_LIST,
};
