const TOTALINFO = [
  {
    label: '数据范围', prop: 'name', align: 'center', minWidth: 160,
  },
  {
    label: '原发不孕占比%', prop: 'yfbyzb', align: 'center',
  },
  { label: '继发不孕占比%', prop: 'jfbyzb', align: 'center' },
  { label: '输卵管因素占比%', prop: 'slgyszb', align: 'center' },
  { label: '排卵障碍占比%', prop: 'plzazb', align: 'center' },
  { label: '卵巢功能衰退占比%', prop: 'lcgnstzb', align: 'center' },
  { label: '子宫内膜异位占比%', prop: 'zgnmywzb', align: 'center' },
  { label: '无精子症占比%', prop: 'wjzzzb', align: 'center' },
  { label: '少弱精子症占比%', prop: 'srjzzzb', align: 'center' },
  { label: '畸精症占比%', prop: 'jjzzb', align: 'center' },
  { label: '不明原因占比%', prop: 'bmyyzb', align: 'center' },
  { label: '双方因素占比%', prop: 'sfyszb', align: 'center' },
  { label: '小于35年龄占比%', prop: 'agexy35zb', align: 'center' },
  { label: '35-39年龄占比%', prop: 'agein3539zb', align: 'center' },
  { label: '40-44年龄占比%', prop: 'agein4044zb', align: 'center' },
  { label: '45-50年龄占比%', prop: 'agein4550zb', align: 'center' },
];

const FIVF = [
  {
    label: '数据范围', prop: 'name', align: 'center', minWidth: 160,
  },
  {
    label: '治疗周期数', prop: 'zlzqs', align: 'center',
  },
  {
    label: '移植周期数', prop: 'yzzqs', align: 'center',
  },
  { label: '平均获卵数', prop: 'pjhls', align: 'center' },
  { label: '2PN受精率%', prop: 'pn2sjl', align: 'center' },
  { label: '优质胚胎率%', prop: 'yzptl', align: 'center' },
  { label: '取消率%', prop: 'qxl', align: 'center' },
  { label: '无可移植胚胎周期率%', prop: 'wkyzptzql', align: 'center' },
  { label: '全胚冷冻率%', prop: 'qpldl', align: 'center' },
  { label: '移植率%', prop: 'yzl', align: 'center' },
  { label: '平均移植胚胎数', prop: 'pjyzpts', align: 'center' },
  { label: '种植率%', prop: 'zzl', align: 'center' },
  { label: '临床妊娠率%', prop: 'lcrsl', align: 'center' },
  { label: '多胎妊娠率%', prop: 'dtrsl', align: 'center' },
  { label: '宫外孕发生率%', prop: 'gwyfsl', align: 'center' },
  { label: '早期流产率%', prop: 'zqlcl', align: 'center' },
  { label: '活产率%', prop: 'hcl', align: 'center' },
  { label: '分娩率%', prop: 'fml', align: 'center' },
  {
    label: '活产胎儿数（男）', prop: 'hctesMale', align: 'center',
  },
  {
    label: '活产胎儿数（女）', prop: 'hctesFamale', align: 'center',
  },
  {
    label: '男女出生比例%', prop: 'sexRatio', align: 'center',
  },
  {
    label: '活产胎儿总数', prop: 'hctezs', align: 'center',
  },
  { label: '出生缺陷发生率%', prop: 'csqxfsl', align: 'center' },
  { label: '并指占比%', prop: 'bzzb', align: 'center' },
  { label: '唇裂占比%', prop: 'clzb', align: 'center' },
  { label: '唇裂合并腭裂占比%', prop: 'clhbelzb', align: 'center' },
  { label: '多指占比%', prop: 'dzzb', align: 'center' },
  { label: '腭裂占比%', prop: 'elzb', align: 'center' },
  { label: '腹裂占比%', prop: 'flzb', align: 'center' },
  { label: '脊柱裂占比%', prop: 'jzlzb', align: 'center' },
  { label: '联体双胎占比%', prop: 'ltstzb', align: 'center' },
  { label: '马蹄内翻足占比%', prop: 'mtnfzzb', align: 'center' },
  { label: '脑膨出占比%', prop: 'npczb', align: 'center' },
  { label: '尿道下裂占比%', prop: 'ndxlzb', align: 'center' },
  { label: '膀胱外翻占比%', prop: 'pgwfzb', align: 'center' },
  { label: '脐膨出占比%', prop: 'qpczb', align: 'center' },
  { label: '食道闭锁或狭窄占比%', prop: 'sdbshxzzb', align: 'center' },
  { label: '唐氏综合症占比%', prop: 'tszhzzb', align: 'center' },
  { label: '无脑畸形占比%', prop: 'wnjxzb', align: 'center' },
  { label: '先天性隔疝占比%', prop: 'xtxgszb', align: 'center' },
  { label: '先天性脑积水占比%', prop: 'xtxnjszb', align: 'center' },
  { label: '先天性心脏病占比%', prop: 'xtxxzbzb', align: 'center' },
  { label: '小耳(包括无耳)占比%', prop: 'xezb', align: 'center' },
  { label: '外耳其他畸形占比%', prop: 'weqtjxzb', align: 'center' },
  { label: '肢体缩短占比%', prop: 'ztsdzb', align: 'center' },
  { label: '直肠肛门闭锁或狭窄占比%', prop: 'zcgmbshxzzb', align: 'center' },
  { label: '其他出生缺陷占比%', prop: 'qtcsqxzb', align: 'center' },
];
const FICSI = [
  {
    label: '数据范围', prop: 'name', align: 'center', minWidth: 160,
  },
  {
    label: '治疗周期数', prop: 'zlzqs', align: 'center',
  },
  {
    label: '移植周期数', prop: 'yzzqs', align: 'center',
  },
  { label: '平均获卵数', prop: 'pjhls', align: 'center' },
  { label: '取消率%', prop: 'qxl', align: 'center' },
  {
    label: 'MII卵总数', prop: 'miilzs', align: 'center',
  },
  { label: 'MII卵率%', prop: 'miilv', align: 'center' },
  { label: '2PN受精率%', prop: 'pn2sjl', align: 'center' },
  { label: '优质胚胎率%', prop: 'yzptl', align: 'center' },
  { label: '无可移植胚胎周期率%', prop: 'wkyzptzql', align: 'center' },
  { label: '全胚冷冻率%', prop: 'qpldl', align: 'center' },
  { label: '移植率%', prop: 'yzl', align: 'center' },
  { label: '平均移植胚胎数', prop: 'pjyzpts', align: 'center' },
  { label: '种植率%', prop: 'zzl', align: 'center' },
  { label: '临床妊娠率%', prop: 'lcrsl', align: 'center' },
  { label: '多胎妊娠率%', prop: 'dtrsl', align: 'center' },
  { label: '宫外孕发生率%', prop: 'gwyfsl', align: 'center' },
  { label: '早期流产率%', prop: 'zqlcl', align: 'center' },
  { label: '活产率%', prop: 'hcl', align: 'center' },
  { label: '分娩率%', prop: 'fml', align: 'center' },
  {
    label: '活产胎儿数（男）', prop: 'hctesMale', align: 'center',
  },
  {
    label: '活产胎儿数（女）', prop: 'hctesFamale', align: 'center',
  },
  {
    label: '男女出生比例%', prop: 'sexRatio', align: 'center',
  },
  {
    label: '活产胎儿总数', prop: 'hctezs', align: 'center',
  },
  { label: '出生缺陷发生率%', prop: 'csqxfsl', align: 'center' },
  { label: '并指占比%', prop: 'bzzb', align: 'center' },
  { label: '唇裂占比%', prop: 'clzb', align: 'center' },
  { label: '唇裂合并腭裂占比%', prop: 'clhbelzb', align: 'center' },
  { label: '多指占比%', prop: 'dzzb', align: 'center' },
  { label: '腭裂占比%', prop: 'elzb', align: 'center' },
  { label: '腹裂占比%', prop: 'flzb', align: 'center' },
  { label: '脊柱裂占比%', prop: 'jzlzb', align: 'center' },
  { label: '联体双胎占比%', prop: 'ltstzb', align: 'center' },
  { label: '马蹄内翻足占比%', prop: 'mtnfzzb', align: 'center' },
  { label: '脑膨出占比%', prop: 'npczb', align: 'center' },
  { label: '尿道下裂占比%', prop: 'ndxlzb', align: 'center' },
  { label: '膀胱外翻占比%', prop: 'pgwfzb', align: 'center' },
  { label: '脐膨出占比%', prop: 'qpczb', align: 'center' },
  { label: '食道闭锁或狭窄占比%', prop: 'sdbshxzzb', align: 'center' },
  { label: '唐氏综合症占比%', prop: 'tszhzzb', align: 'center' },
  { label: '无脑畸形占比%', prop: 'wnjxzb', align: 'center' },
  { label: '先天性隔疝占比%', prop: 'xtxgszb', align: 'center' },
  { label: '先天性脑积水占比%', prop: 'xtxnjszb', align: 'center' },
  { label: '先天性心脏病占比%', prop: 'xtxxzbzb', align: 'center' },
  { label: '小耳(包括无耳)占比%', prop: 'xezb', align: 'center' },
  { label: '外耳其他畸形占比%', prop: 'weqtjxzb', align: 'center' },
  { label: '肢体缩短占比%', prop: 'ztsdzb', align: 'center' },
  { label: '直肠肛门闭锁或狭窄占比%', prop: 'zcgmbshxzzb', align: 'center' },
  { label: '其他出生缺陷占比%', prop: 'qtcsqxzb', align: 'center' },
];

const FIVFICSI = [
  {
    label: '数据范围', prop: 'name', align: 'center', minWidth: 160,
  },
  {
    label: '治疗周期数', prop: 'zlzqs', align: 'center',
  },
  {
    label: '移植周期数', prop: 'yzzqs', align: 'center',
  },
  { label: '平均获卵数', prop: 'pjhls', align: 'center' },
  { label: '平均移植胚胎数', prop: 'pjyzpts', align: 'center' },
  { label: '取消率%', prop: 'qxl', align: 'center' },
  { label: '2PN受精率%', prop: 'pn2sjl', align: 'center' },
  { label: '优质胚胎率%', prop: 'yzptl', align: 'center' },
  { label: '无可移植胚胎周期率%', prop: 'wkyzptzql', align: 'center' },
  { label: '全胚冷冻率%', prop: 'qpldl', align: 'center' },
  { label: '移植率%', prop: 'yzl', align: 'center' },
  { label: '种植率%', prop: 'zzl', align: 'center' },
  { label: '临床妊娠率%', prop: 'lcrsl', align: 'center' },
  { label: '多胎妊娠率%', prop: 'dtrsl', align: 'center' },
  { label: '宫外孕发生率%', prop: 'gwyfsl', align: 'center' },
  { label: '早期流产率%', prop: 'zqlcl', align: 'center' },
  { label: '活产率%', prop: 'hcl', align: 'center' },
  { label: '分娩率%', prop: 'fml', align: 'center' },
  {
    label: '活产胎儿数（男）', prop: 'hctesMale', align: 'center',
  },
  {
    label: '活产胎儿数（女）', prop: 'hctesFamale', align: 'center',
  },
  {
    label: '男女出生比例%', prop: 'sexRatio', align: 'center',
  },
  {
    label: '活产胎儿总数', prop: 'hctezs', align: 'center',
  },
  { label: '出生缺陷发生率%', prop: 'csqxfsl', align: 'center' },
  { label: '并指占比%', prop: 'bzzb', align: 'center' },
  { label: '唇裂占比%', prop: 'clzb', align: 'center' },
  { label: '唇裂合并腭裂占比%', prop: 'clhbelzb', align: 'center' },
  { label: '多指占比%', prop: 'dzzb', align: 'center' },
  { label: '腭裂占比%', prop: 'elzb', align: 'center' },
  { label: '腹裂占比%', prop: 'flzb', align: 'center' },
  { label: '脊柱裂占比%', prop: 'jzlzb', align: 'center' },
  { label: '联体双胎占比%', prop: 'ltstzb', align: 'center' },
  { label: '马蹄内翻足占比%', prop: 'mtnfzzb', align: 'center' },
  { label: '脑膨出占比%', prop: 'npczb', align: 'center' },
  { label: '尿道下裂占比%', prop: 'ndxlzb', align: 'center' },
  { label: '膀胱外翻占比%', prop: 'pgwfzb', align: 'center' },
  { label: '脐膨出占比%', prop: 'qpczb', align: 'center' },
  { label: '食道闭锁或狭窄占比%', prop: 'sdbshxzzb', align: 'center' },
  { label: '唐氏综合症占比%', prop: 'tszhzzb', align: 'center' },
  { label: '无脑畸形占比%', prop: 'wnjxzb', align: 'center' },
  { label: '先天性隔疝占比%', prop: 'xtxgszb', align: 'center' },
  { label: '先天性脑积水占比%', prop: 'xtxnjszb', align: 'center' },
  { label: '先天性心脏病占比%', prop: 'xtxxzbzb', align: 'center' },
  { label: '小耳(包括无耳)占比%', prop: 'xezb', align: 'center' },
  { label: '外耳其他畸形占比%', prop: 'weqtjxzb', align: 'center' },
  { label: '肢体缩短占比%', prop: 'ztsdzb', align: 'center' },
  { label: '直肠肛门闭锁或狭窄占比%', prop: 'zcgmbshxzzb', align: 'center' },
  { label: '其他出生缺陷占比%', prop: 'qtcsqxzb', align: 'center' },
];

const GIVF = [
  {
    label: '数据范围', prop: 'name', align: 'center', minWidth: 160,
  },
  {
    label: '治疗周期数', prop: 'zlzqs', align: 'center',
  },
  {
    label: '移植周期数', prop: 'yzzqs', align: 'center',
  },
  { label: '平均获卵数', prop: 'pjhls', align: 'center' },
  { label: '平均移植胚胎数', prop: 'pjyzpts', align: 'center' },
  { label: '2PN受精率%', prop: 'pn2sjl', align: 'center' },
  { label: '优质胚胎率%', prop: 'yzptl', align: 'center' },
  { label: '取消率%', prop: 'qxl', align: 'center' },
  { label: '无可移植胚胎周期率%', prop: 'wkyzptzql', align: 'center' },
  { label: '全胚冷冻率%', prop: 'qpldl', align: 'center' },
  { label: '移植率%', prop: 'yzl', align: 'center' },
  { label: '种植率%', prop: 'zzl', align: 'center' },
  { label: '临床妊娠率%', prop: 'lcrsl', align: 'center' },
  { label: '多胎妊娠率%', prop: 'dtrsl', align: 'center' },
  { label: '宫外孕发生率%', prop: 'gwyfsl', align: 'center' },
  { label: '早期流产率%', prop: 'zqlcl', align: 'center' },
  { label: '活产率%', prop: 'hcl', align: 'center' },
  { label: '分娩率%', prop: 'fml', align: 'center' },
  {
    label: '活产胎儿数（男）', prop: 'hctesMale', align: 'center',
  },
  {
    label: '活产胎儿数（女）', prop: 'hctesFamale', align: 'center',
  },
  {
    label: '男女出生比例%', prop: 'sexRatio', align: 'center',
  },
  {
    label: '活产胎儿总数', prop: 'hctezs', align: 'center',
  },
  { label: '出生缺陷发生率%', prop: 'csqxfsl', align: 'center' },
  { label: '并指占比%', prop: 'bzzb', align: 'center' },
  { label: '唇裂占比%', prop: 'clzb', align: 'center' },
  { label: '唇裂合并腭裂占比%', prop: 'clhbelzb', align: 'center' },
  { label: '多指占比%', prop: 'dzzb', align: 'center' },
  { label: '腭裂占比%', prop: 'elzb', align: 'center' },
  { label: '腹裂占比%', prop: 'flzb', align: 'center' },
  { label: '脊柱裂占比%', prop: 'jzlzb', align: 'center' },
  { label: '联体双胎占比%', prop: 'ltstzb', align: 'center' },
  { label: '马蹄内翻足占比%', prop: 'mtnfzzb', align: 'center' },
  { label: '脑膨出占比%', prop: 'npczb', align: 'center' },
  { label: '尿道下裂占比%', prop: 'ndxlzb', align: 'center' },
  { label: '膀胱外翻占比%', prop: 'pgwfzb', align: 'center' },
  { label: '脐膨出占比%', prop: 'qpczb', align: 'center' },
  { label: '食道闭锁或狭窄占比%', prop: 'sdbshxzzb', align: 'center' },
  { label: '唐氏综合症占比%', prop: 'tszhzzb', align: 'center' },
  { label: '无脑畸形占比%', prop: 'wnjxzb', align: 'center' },
  { label: '先天性隔疝占比%', prop: 'xtxgszb', align: 'center' },
  { label: '先天性脑积水占比%', prop: 'xtxnjszb', align: 'center' },
  { label: '先天性心脏病占比%', prop: 'xtxxzbzb', align: 'center' },
  { label: '小耳(包括无耳)占比%', prop: 'xezb', align: 'center' },
  { label: '外耳其他畸形占比%', prop: 'weqtjxzb', align: 'center' },
  { label: '肢体缩短占比%', prop: 'ztsdzb', align: 'center' },
  { label: '直肠肛门闭锁或狭窄占比%', prop: 'zcgmbshxzzb', align: 'center' },
  { label: '其他出生缺陷占比%', prop: 'qtcsqxzb', align: 'center' },
];

const FET = [
  {
    label: '数据范围', prop: 'name', align: 'center', minWidth: 160,
  },
  {
    label: '复苏周期数', prop: 'fszqs', align: 'center',
  },
  { label: '复苏率%', prop: 'fsl', align: 'center' },
  {
    label: '移植周期数', prop: 'yzzqs', align: 'center',
  },
  { label: '平均移植胚胎数', prop: 'pjyzpts', align: 'center' },
  { label: '种植率%', prop: 'zzl', align: 'center' },
  { label: '临床妊娠率%', prop: 'lcrsl', align: 'center' },
  { label: '多胎妊娠率%', prop: 'dtrsl', align: 'center' },
  { label: '宫外孕发生率%', prop: 'gwyfsl', align: 'center' },
  { label: '早期流产率%', prop: 'zqlcl', align: 'center' },
  { label: '活产率%', prop: 'hcl', align: 'center' },
  { label: '分娩率%', prop: 'fml', align: 'center' },
  {
    label: '活产胎儿数（男）', prop: 'hctesMale', align: 'center',
  },
  {
    label: '活产胎儿数（女）', prop: 'hctesFamale', align: 'center',
  },
  {
    label: '男女出生比例%', prop: 'sexRatio', align: 'center',
  },
  {
    label: '活产胎儿总数', prop: 'hctezs', align: 'center',
  },
  { label: '出生缺陷发生率%', prop: 'csqxfsl', align: 'center' },
  { label: '并指占比%', prop: 'bzzb', align: 'center' },
  { label: '唇裂占比%', prop: 'clzb', align: 'center' },
  { label: '唇裂合并腭裂占比%', prop: 'clhbelzb', align: 'center' },
  { label: '多指占比%', prop: 'dzzb', align: 'center' },
  { label: '腭裂占比%', prop: 'elzb', align: 'center' },
  { label: '腹裂占比%', prop: 'flzb', align: 'center' },
  { label: '脊柱裂占比%', prop: 'jzlzb', align: 'center' },
  { label: '联体双胎占比%', prop: 'ltstzb', align: 'center' },
  { label: '马蹄内翻足占比%', prop: 'mtnfzzb', align: 'center' },
  { label: '脑膨出占比%', prop: 'npczb', align: 'center' },
  { label: '尿道下裂占比%', prop: 'ndxlzb', align: 'center' },
  { label: '膀胱外翻占比%', prop: 'pgwfzb', align: 'center' },
  { label: '脐膨出占比%', prop: 'qpczb', align: 'center' },
  { label: '食道闭锁或狭窄占比%', prop: 'sdbshxzzb', align: 'center' },
  { label: '唐氏综合症占比%', prop: 'tszhzzb', align: 'center' },
  { label: '无脑畸形占比%', prop: 'wnjxzb', align: 'center' },
  { label: '先天性隔疝占比%', prop: 'xtxgszb', align: 'center' },
  { label: '先天性脑积水占比%', prop: 'xtxnjszb', align: 'center' },
  { label: '先天性心脏病占比%', prop: 'xtxxzbzb', align: 'center' },
  { label: '小耳(包括无耳)占比%', prop: 'xezb', align: 'center' },
  { label: '外耳其他畸形占比%', prop: 'weqtjxzb', align: 'center' },
  { label: '肢体缩短占比%', prop: 'ztsdzb', align: 'center' },
  { label: '直肠肛门闭锁或狭窄占比%', prop: 'zcgmbshxzzb', align: 'center' },
  { label: '其他出生缺陷占比%', prop: 'qtcsqxzb', align: 'center' },
];

const PGTA = [
  {
    label: '数据范围', prop: 'name', align: 'center', minWidth: 160,
  },
  {
    label: '治疗周期数', prop: 'zlzqs', align: 'center',
  },
  {
    label: '移植周期数', prop: 'yzzqs', align: 'center',
  },
  { label: '平均移植胚胎数', prop: 'pjyzpts', align: 'center' },
  { label: '平均获卵数', prop: 'pjhls', align: 'center' },
  { label: '2PN受精率%', prop: 'pn2sjl', align: 'center' },
  { label: '卵裂率%', prop: 'lll', align: 'center' },
  { label: '活检胚胎率%', prop: 'hjptl', align: 'center' },
  { label: '可移植胚胎率%', prop: 'kyzptl', align: 'center' },
  { label: '羊穿比例%', prop: 'ycbl', align: 'center' },
  { label: '羊穿结果与胚胎检测结果一致率%', prop: 'ycjgyptjcjgyzl', align: 'center' },
  { label: '种植率%', prop: 'zzl', align: 'center' },
  { label: '临床妊娠率%', prop: 'lcrsl', align: 'center' },
  { label: '多胎妊娠率%', prop: 'dtrsl', align: 'center' },
  { label: '宫外孕发生率%', prop: 'gwyfsl', align: 'center' },
  { label: '早期流产率%', prop: 'zqlcl', align: 'center' },
  { label: '活产率%', prop: 'hcl', align: 'center' },
  { label: '分娩率%', prop: 'fml', align: 'center' },
  {
    label: '活产胎儿数（男）', prop: 'hctesMale', align: 'center',
  },
  {
    label: '活产胎儿数（女）', prop: 'hctesFamale', align: 'center',
  },
  {
    label: '男女出生比例%', prop: 'sexRatio', align: 'center',
  },
  {
    label: '活产胎儿总数', prop: 'hctezs', align: 'center',
  },
  { label: '出生缺陷发生率%', prop: 'csqxfsl', align: 'center' },
  { label: '并指占比%', prop: 'bzzb', align: 'center' },
  { label: '唇裂占比%', prop: 'clzb', align: 'center' },
  { label: '唇裂合并腭裂占比%', prop: 'clhbelzb', align: 'center' },
  { label: '多指占比%', prop: 'dzzb', align: 'center' },
  { label: '腭裂占比%', prop: 'elzb', align: 'center' },
  { label: '腹裂占比%', prop: 'flzb', align: 'center' },
  { label: '脊柱裂占比%', prop: 'jzlzb', align: 'center' },
  { label: '联体双胎占比%', prop: 'ltstzb', align: 'center' },
  { label: '马蹄内翻足占比%', prop: 'mtnfzzb', align: 'center' },
  { label: '脑膨出占比%', prop: 'npczb', align: 'center' },
  { label: '尿道下裂占比%', prop: 'ndxlzb', align: 'center' },
  { label: '膀胱外翻占比%', prop: 'pgwfzb', align: 'center' },
  { label: '脐膨出占比%', prop: 'qpczb', align: 'center' },
  { label: '食道闭锁或狭窄占比%', prop: 'sdbshxzzb', align: 'center' },
  { label: '唐氏综合症占比%', prop: 'tszhzzb', align: 'center' },
  { label: '无脑畸形占比%', prop: 'wnjxzb', align: 'center' },
  { label: '先天性隔疝占比%', prop: 'xtxgszb', align: 'center' },
  { label: '先天性脑积水占比%', prop: 'xtxnjszb', align: 'center' },
  { label: '先天性心脏病占比%', prop: 'xtxxzbzb', align: 'center' },
  { label: '小耳(包括无耳)占比%', prop: 'xezb', align: 'center' },
  { label: '外耳其他畸形占比%', prop: 'weqtjxzb', align: 'center' },
  { label: '肢体缩短占比%', prop: 'ztsdzb', align: 'center' },
  { label: '直肠肛门闭锁或狭窄占比%', prop: 'zcgmbshxzzb', align: 'center' },
  { label: '其他出生缺陷占比%', prop: 'qtcsqxzb', align: 'center' },
];


const PGTSR = [
  {
    label: '数据范围', prop: 'name', align: 'center', minWidth: 160,
  },
  {
    label: '治疗周期数', prop: 'zlzqs', align: 'center',
  },
  {
    label: '移植周期数', prop: 'yzzqs', align: 'center',
  },
  { label: '平均移植胚胎数', prop: 'pjyzpts', align: 'center' },
  { label: '平均获卵数', prop: 'pjhls', align: 'center' },
  { label: '2PN受精率%', prop: 'pn2sjl', align: 'center' },
  { label: '卵裂率%', prop: 'lll', align: 'center' },
  { label: '活检胚胎率%', prop: 'hjptl', align: 'center' },
  { label: '可移植胚胎率%', prop: 'kyzptl', align: 'center' },
  { label: '羊穿比例%', prop: 'ycbl', align: 'center' },
  { label: '羊穿结果与胚胎检测结果一致率%', prop: 'ycjgyptjcjgyzl', align: 'center' },
  { label: '种植率%', prop: 'zzl', align: 'center' },
  { label: '临床妊娠率%', prop: 'lcrsl', align: 'center' },
  { label: '多胎妊娠率%', prop: 'dtrsl', align: 'center' },
  { label: '宫外孕发生率%', prop: 'gwyfsl', align: 'center' },
  { label: '早期流产率%', prop: 'zqlcl', align: 'center' },
  { label: '活产率%', prop: 'hcl', align: 'center' },
  { label: '分娩率%', prop: 'fml', align: 'center' },
  {
    label: '活产胎儿数（男）', prop: 'hctesMale', align: 'center',
  },
  {
    label: '活产胎儿数（女）', prop: 'hctesFamale', align: 'center',
  },
  {
    label: '男女出生比例%', prop: 'sexRatio', align: 'center',
  },
  {
    label: '活产胎儿总数', prop: 'hctezs', align: 'center',
  },
  { label: '出生缺陷发生率%', prop: 'csqxfsl', align: 'center' },
  { label: '并指占比%', prop: 'bzzb', align: 'center' },
  { label: '唇裂占比%', prop: 'clzb', align: 'center' },
  { label: '唇裂合并腭裂占比%', prop: 'clhbelzb', align: 'center' },
  { label: '多指占比%', prop: 'dzzb', align: 'center' },
  { label: '腭裂占比%', prop: 'elzb', align: 'center' },
  { label: '腹裂占比%', prop: 'flzb', align: 'center' },
  { label: '脊柱裂占比%', prop: 'jzlzb', align: 'center' },
  { label: '联体双胎占比%', prop: 'ltstzb', align: 'center' },
  { label: '马蹄内翻足占比%', prop: 'mtnfzzb', align: 'center' },
  { label: '脑膨出占比%', prop: 'npczb', align: 'center' },
  { label: '尿道下裂占比%', prop: 'ndxlzb', align: 'center' },
  { label: '膀胱外翻占比%', prop: 'pgwfzb', align: 'center' },
  { label: '脐膨出占比%', prop: 'qpczb', align: 'center' },
  { label: '食道闭锁或狭窄占比%', prop: 'sdbshxzzb', align: 'center' },
  { label: '唐氏综合症占比%', prop: 'tszhzzb', align: 'center' },
  { label: '无脑畸形占比%', prop: 'wnjxzb', align: 'center' },
  { label: '先天性隔疝占比%', prop: 'xtxgszb', align: 'center' },
  { label: '先天性脑积水占比%', prop: 'xtxnjszb', align: 'center' },
  { label: '先天性心脏病占比%', prop: 'xtxxzbzb', align: 'center' },
  { label: '小耳(包括无耳)占比%', prop: 'xezb', align: 'center' },
  { label: '外耳其他畸形占比%', prop: 'weqtjxzb', align: 'center' },
  { label: '肢体缩短占比%', prop: 'ztsdzb', align: 'center' },
  { label: '直肠肛门闭锁或狭窄占比%', prop: 'zcgmbshxzzb', align: 'center' },
  { label: '其他出生缺陷占比%', prop: 'qtcsqxzb', align: 'center' },
];


const PGTM = [
  {
    label: '数据范围', prop: 'name', align: 'center', minWidth: 160,
  },
  {
    label: '治疗周期数', prop: 'zlzqs', align: 'center',
  },
  {
    label: '移植周期数', prop: 'yzzqs', align: 'center',
  },
  { label: '平均移植胚胎数', prop: 'pjyzpts', align: 'center' },
  { label: '平均获卵数', prop: 'pjhls', align: 'center' },
  { label: '2PN受精率%', prop: 'pn2sjl', align: 'center' },
  { label: '卵裂率%', prop: 'lll', align: 'center' },
  { label: '活检胚胎率%', prop: 'hjptl', align: 'center' },
  { label: '可移植胚胎率%', prop: 'kyzptl', align: 'center' },
  { label: '羊穿比例%', prop: 'ycbl', align: 'center' },
  { label: '羊穿结果与胚胎检测结果一致率%', prop: 'ycjgyptjcjgyzl', align: 'center' },
  { label: '种植率%', prop: 'zzl', align: 'center' },
  { label: '临床妊娠率%', prop: 'lcrsl', align: 'center' },
  { label: '多胎妊娠率%', prop: 'dtrsl', align: 'center' },
  { label: '宫外孕发生率%', prop: 'gwyfsl', align: 'center' },
  { label: '早期流产率%', prop: 'zqlcl', align: 'center' },
  { label: '活产率%', prop: 'hcl', align: 'center' },
  { label: '分娩率%', prop: 'fml', align: 'center' },
  {
    label: '活产胎儿数（男）', prop: 'hctesMale', align: 'center',
  },
  {
    label: '活产胎儿数（女）', prop: 'hctesFamale', align: 'center',
  },
  {
    label: '男女出生比例%', prop: 'sexRatio', align: 'center',
  },
  {
    label: '活产胎儿总数', prop: 'hctezs', align: 'center',
  },
  { label: '出生缺陷发生率%', prop: 'csqxfsl', align: 'center' },
  { label: '并指占比%', prop: 'bzzb', align: 'center' },
  { label: '唇裂占比%', prop: 'clzb', align: 'center' },
  { label: '唇裂合并腭裂占比%', prop: 'clhbelzb', align: 'center' },
  { label: '多指占比%', prop: 'dzzb', align: 'center' },
  { label: '腭裂占比%', prop: 'elzb', align: 'center' },
  { label: '腹裂占比%', prop: 'flzb', align: 'center' },
  { label: '脊柱裂占比%', prop: 'jzlzb', align: 'center' },
  { label: '联体双胎占比%', prop: 'ltstzb', align: 'center' },
  { label: '马蹄内翻足占比%', prop: 'mtnfzzb', align: 'center' },
  { label: '脑膨出占比%', prop: 'npczb', align: 'center' },
  { label: '尿道下裂占比%', prop: 'ndxlzb', align: 'center' },
  { label: '膀胱外翻占比%', prop: 'pgwfzb', align: 'center' },
  { label: '脐膨出占比%', prop: 'qpczb', align: 'center' },
  { label: '食道闭锁或狭窄占比%', prop: 'sdbshxzzb', align: 'center' },
  { label: '唐氏综合症占比%', prop: 'tszhzzb', align: 'center' },
  { label: '无脑畸形占比%', prop: 'wnjxzb', align: 'center' },
  { label: '先天性隔疝占比%', prop: 'xtxgszb', align: 'center' },
  { label: '先天性脑积水占比%', prop: 'xtxnjszb', align: 'center' },
  { label: '先天性心脏病占比%', prop: 'xtxxzbzb', align: 'center' },
  { label: '小耳(包括无耳)占比%', prop: 'xezb', align: 'center' },
  { label: '外耳其他畸形占比%', prop: 'weqtjxzb', align: 'center' },
  { label: '肢体缩短占比%', prop: 'ztsdzb', align: 'center' },
  { label: '直肠肛门闭锁或狭窄占比%', prop: 'zcgmbshxzzb', align: 'center' },
  { label: '其他出生缺陷占比%', prop: 'qtcsqxzb', align: 'center' },
];

const AIH = [
  {
    label: '数据范围', prop: 'name', align: 'center', minWidth: 160,
  },
  {
    label: '治疗周期数', prop: 'zlzqs', align: 'center',
  },
  { label: '临床妊娠率%', prop: 'lcrsl', align: 'center' },
  { label: '多胎妊娠率%', prop: 'dtrsl', align: 'center' },
  { label: '宫外孕发生率%', prop: 'gwyfsl', align: 'center' },
  { label: '早期流产率%', prop: 'zqlcl', align: 'center' },
  { label: '活产率%', prop: 'hcl', align: 'center' },
  { label: '分娩率%', prop: 'fml', align: 'center' },
  {
    label: '活产胎儿数（男）', prop: 'hctesMale', align: 'center',
  },
  {
    label: '活产胎儿数（女）', prop: 'hctesFamale', align: 'center',
  },
  {
    label: '男女出生比例%', prop: 'sexRatio', align: 'center',
  },
  {
    label: '活产胎儿总数', prop: 'hctezs', align: 'center',
  },
  { label: '出生缺陷发生率%', prop: 'csqxfsl', align: 'center' },
  { label: '并指占比%', prop: 'bzzb', align: 'center' },
  { label: '唇裂占比%', prop: 'clzb', align: 'center' },
  { label: '唇裂合并腭裂占比%', prop: 'clhbelzb', align: 'center' },
  { label: '多指占比%', prop: 'dzzb', align: 'center' },
  { label: '腭裂占比%', prop: 'elzb', align: 'center' },
  { label: '腹裂占比%', prop: 'flzb', align: 'center' },
  { label: '脊柱裂占比%', prop: 'jzlzb', align: 'center' },
  { label: '联体双胎占比%', prop: 'ltstzb', align: 'center' },
  { label: '马蹄内翻足占比%', prop: 'mtnfzzb', align: 'center' },
  { label: '脑膨出占比%', prop: 'npczb', align: 'center' },
  { label: '尿道下裂占比%', prop: 'ndxlzb', align: 'center' },
  { label: '膀胱外翻占比%', prop: 'pgwfzb', align: 'center' },
  { label: '脐膨出占比%', prop: 'qpczb', align: 'center' },
  { label: '食道闭锁或狭窄占比%', prop: 'sdbshxzzb', align: 'center' },
  { label: '唐氏综合症占比%', prop: 'tszhzzb', align: 'center' },
  { label: '无脑畸形占比%', prop: 'wnjxzb', align: 'center' },
  { label: '先天性隔疝占比%', prop: 'xtxgszb', align: 'center' },
  { label: '先天性脑积水占比%', prop: 'xtxnjszb', align: 'center' },
  { label: '先天性心脏病占比%', prop: 'xtxxzbzb', align: 'center' },
  { label: '小耳(包括无耳)占比%', prop: 'xezb', align: 'center' },
  { label: '外耳其他畸形占比%', prop: 'weqtjxzb', align: 'center' },
  { label: '肢体缩短占比%', prop: 'ztsdzb', align: 'center' },
  { label: '直肠肛门闭锁或狭窄占比%', prop: 'zcgmbshxzzb', align: 'center' },
  { label: '其他出生缺陷占比%', prop: 'qtcsqxzb', align: 'center' },
];

const AID = [
  {
    label: '数据范围', prop: 'name', align: 'center', minWidth: 160,
  },
  {
    label: '治疗周期数', prop: 'zlzqs', align: 'center',
  },
  { label: '临床妊娠率%', prop: 'lcrsl', align: 'center' },
  { label: '多胎妊娠率%', prop: 'dtrsl', align: 'center' },
  { label: '宫外孕发生率%', prop: 'gwyfsl', align: 'center' },
  { label: '早期流产率%', prop: 'zqlcl', align: 'center' },
  { label: '活产率%', prop: 'hcl', align: 'center' },
  { label: '分娩率%', prop: 'fml', align: 'center' },
  {
    label: '活产胎儿数（男）', prop: 'hctesMale', align: 'center',
  },
  {
    label: '活产胎儿数（女）', prop: 'hctesFamale', align: 'center',
  },
  {
    label: '男女出生比例%', prop: 'sexRatio', align: 'center',
  },
  {
    label: '活产胎儿总数', prop: 'hctezs', align: 'center',
  },
  { label: '出生缺陷发生率%', prop: 'csqxfsl', align: 'center' },
  { label: '并指占比%', prop: 'bzzb', align: 'center' },
  { label: '唇裂占比%', prop: 'clzb', align: 'center' },
  { label: '唇裂合并腭裂占比%', prop: 'clhbelzb', align: 'center' },
  { label: '多指占比%', prop: 'dzzb', align: 'center' },
  { label: '腭裂占比%', prop: 'elzb', align: 'center' },
  { label: '腹裂占比%', prop: 'flzb', align: 'center' },
  { label: '脊柱裂占比%', prop: 'jzlzb', align: 'center' },
  { label: '联体双胎占比%', prop: 'ltstzb', align: 'center' },
  { label: '马蹄内翻足占比%', prop: 'mtnfzzb', align: 'center' },
  { label: '脑膨出占比%', prop: 'npczb', align: 'center' },
  { label: '尿道下裂占比%', prop: 'ndxlzb', align: 'center' },
  { label: '膀胱外翻占比%', prop: 'pgwfzb', align: 'center' },
  { label: '脐膨出占比%', prop: 'qpczb', align: 'center' },
  { label: '食道闭锁或狭窄占比%', prop: 'sdbshxzzb', align: 'center' },
  { label: '唐氏综合症占比%', prop: 'tszhzzb', align: 'center' },
  { label: '无脑畸形占比%', prop: 'wnjxzb', align: 'center' },
  { label: '先天性隔疝占比%', prop: 'xtxgszb', align: 'center' },
  { label: '先天性脑积水占比%', prop: 'xtxnjszb', align: 'center' },
  { label: '先天性心脏病占比%', prop: 'xtxxzbzb', align: 'center' },
  { label: '小耳(包括无耳)占比%', prop: 'xezb', align: 'center' },
  { label: '外耳其他畸形占比%', prop: 'weqtjxzb', align: 'center' },
  { label: '肢体缩短占比%', prop: 'ztsdzb', align: 'center' },
  { label: '直肠肛门闭锁或狭窄占比%', prop: 'zcgmbshxzzb', align: 'center' },
  { label: '其他出生缺陷占比%', prop: 'qtcsqxzb', align: 'center' },
];

const ZSL = [
  {
    label: '数据范围', prop: 'name', align: 'center', minWidth: 160,
  },
  {
    label: '赠卵周期数', prop: 'zlzqs', align: 'center',
  },
  {
    label: '移植周期数', prop: 'yzzqs', align: 'center',
  },
  { label: '正常受精率%', prop: 'zcsjl', align: 'center' },
  { label: '平均移植胚胎数', prop: 'pjyzpts', align: 'center' },
  { label: '种植率%', prop: 'zzl', align: 'center' },
  { label: '临床妊娠率%', prop: 'lcrsl', align: 'center' },
  { label: '多胎妊娠率%', prop: 'dtrsl', align: 'center' },
  { label: '宫外孕发生率%', prop: 'gwyfsl', align: 'center' },
  { label: '早期流产率%', prop: 'zqlcl', align: 'center' },
  { label: '活产率%', prop: 'hcl', align: 'center' },
  { label: '分娩率%', prop: 'fml', align: 'center' },
  {
    label: '活产胎儿数（男）', prop: 'hctesMale', align: 'center',
  },
  {
    label: '活产胎儿数（女）', prop: 'hctesFamale', align: 'center',
  },
  {
    label: '男女出生比例%', prop: 'sexRatio', align: 'center',
  },
  {
    label: '活产胎儿总数', prop: 'hctezs', align: 'center',
  },
  { label: '出生缺陷发生率%', prop: 'csqxfsl', align: 'center' },
  { label: '并指占比%', prop: 'bzzb', align: 'center' },
  { label: '唇裂占比%', prop: 'clzb', align: 'center' },
  { label: '唇裂合并腭裂占比%', prop: 'clhbelzb', align: 'center' },
  { label: '多指占比%', prop: 'dzzb', align: 'center' },
  { label: '腭裂占比%', prop: 'elzb', align: 'center' },
  { label: '腹裂占比%', prop: 'flzb', align: 'center' },
  { label: '脊柱裂占比%', prop: 'jzlzb', align: 'center' },
  { label: '联体双胎占比%', prop: 'ltstzb', align: 'center' },
  { label: '马蹄内翻足占比%', prop: 'mtnfzzb', align: 'center' },
  { label: '脑膨出占比%', prop: 'npczb', align: 'center' },
  { label: '尿道下裂占比%', prop: 'ndxlzb', align: 'center' },
  { label: '膀胱外翻占比%', prop: 'pgwfzb', align: 'center' },
  { label: '脐膨出占比%', prop: 'qpczb', align: 'center' },
  { label: '食道闭锁或狭窄占比%', prop: 'sdbshxzzb', align: 'center' },
  { label: '唐氏综合症占比%', prop: 'tszhzzb', align: 'center' },
  { label: '无脑畸形占比%', prop: 'wnjxzb', align: 'center' },
  { label: '先天性隔疝占比%', prop: 'xtxgszb', align: 'center' },
  { label: '先天性脑积水占比%', prop: 'xtxnjszb', align: 'center' },
  { label: '先天性心脏病占比%', prop: 'xtxxzbzb', align: 'center' },
  { label: '小耳(包括无耳)占比%', prop: 'xezb', align: 'center' },
  { label: '外耳其他畸形占比%', prop: 'weqtjxzb', align: 'center' },
  { label: '肢体缩短占比%', prop: 'ztsdzb', align: 'center' },
  { label: '直肠肛门闭锁或狭窄占比%', prop: 'zcgmbshxzzb', align: 'center' },
  { label: '其他出生缺陷占比%', prop: 'qtcsqxzb', align: 'center' },
];

const DRL = [
  {
    label: '数据范围', prop: 'name', align: 'center', minWidth: 160,
  },
  {
    label: '冻卵周期数', prop: 'dlzqs', align: 'center',
  },
  {
    label: '冷冻卵子数', prop: 'ldlzs', align: 'center',
  },
  {
    label: '融卵周期数', prop: 'rlzqs', align: 'center',
  },
  { label: '卵子复苏率%', prop: 'lzfsl', align: 'center' },
  { label: 'PN2受精率%', prop: 'pn2sjl', align: 'center' },
  { label: '优质胚胎率%', prop: 'yzptl', align: 'center' },
  { label: '有效胚胎率%', prop: 'yxptl', align: 'center' },
  { label: '平均移植胚胎数', prop: 'pjyzpts', align: 'center' },
  { label: '种植率%', prop: 'zzl', align: 'center' },
  { label: '临床妊娠率%', prop: 'lcrsl', align: 'center' },
  { label: '多胎妊娠率%', prop: 'dtrsl', align: 'center' },
  { label: '宫外孕发生率%', prop: 'gwyfsl', align: 'center' },
  { label: '早期流产率%', prop: 'zqlcl', align: 'center' },
  { label: '活产率%', prop: 'hcl', align: 'center' },
  { label: '分娩率%', prop: 'fml', align: 'center' },
  {
    label: '活产胎儿数（男）', prop: 'hctesMale', align: 'center',
  },
  {
    label: '活产胎儿数（女）', prop: 'hctesFamale', align: 'center',
  },
  {
    label: '男女出生比例%', prop: 'sexRatio', align: 'center',
  },
  {
    label: '活产胎儿总数', prop: 'hctezs', align: 'center',
  },
  { label: '出生缺陷发生率%', prop: 'csqxfsl', align: 'center' },
  { label: '并指占比%', prop: 'bzzb', align: 'center' },
  { label: '唇裂占比%', prop: 'clzb', align: 'center' },
  { label: '唇裂合并腭裂占比%', prop: 'clhbelzb', align: 'center' },
  { label: '多指占比%', prop: 'dzzb', align: 'center' },
  { label: '腭裂占比%', prop: 'elzb', align: 'center' },
  { label: '腹裂占比%', prop: 'flzb', align: 'center' },
  { label: '脊柱裂占比%', prop: 'jzlzb', align: 'center' },
  { label: '联体双胎占比%', prop: 'ltstzb', align: 'center' },
  { label: '马蹄内翻足占比%', prop: 'mtnfzzb', align: 'center' },
  { label: '脑膨出占比%', prop: 'npczb', align: 'center' },
  { label: '尿道下裂占比%', prop: 'ndxlzb', align: 'center' },
  { label: '膀胱外翻占比%', prop: 'pgwfzb', align: 'center' },
  { label: '脐膨出占比%', prop: 'qpczb', align: 'center' },
  { label: '食道闭锁或狭窄占比%', prop: 'sdbshxzzb', align: 'center' },
  { label: '唐氏综合症占比%', prop: 'tszhzzb', align: 'center' },
  { label: '无脑畸形占比%', prop: 'wnjxzb', align: 'center' },
  { label: '先天性隔疝占比%', prop: 'xtxgszb', align: 'center' },
  { label: '先天性脑积水占比%', prop: 'xtxnjszb', align: 'center' },
  { label: '先天性心脏病占比%', prop: 'xtxxzbzb', align: 'center' },
  { label: '小耳(包括无耳)占比%', prop: 'xezb', align: 'center' },
  { label: '外耳其他畸形占比%', prop: 'weqtjxzb', align: 'center' },
  { label: '肢体缩短占比%', prop: 'ztsdzb', align: 'center' },
  { label: '直肠肛门闭锁或狭窄占比%', prop: 'zcgmbshxzzb', align: 'center' },
  { label: '其他出生缺陷占比%', prop: 'qtcsqxzb', align: 'center' },
];

const NUM_COL = ['name', 'zlzqs', 'yzzqs', 'hctesMale', 'hctesFamale', 'sexRatio', 'hctezs', 'miilzs', 'fszqs', 'dlzqs', 'ldlzs', 'rlzqs'];

const COL_CONIFGS = {
  TotalInfo: TOTALINFO,
  FuJingIvf: FIVF,
  FuJingIcsi: FICSI,
  FuJingIvfIcsi: FIVFICSI,
  GongJingIvf: GIVF,
  Fet: FET,
  Pgta: PGTA,
  Pgtsr: PGTSR,
  Pgtm: PGTM,
  Aih: AIH,
  Aid: AID,
  ZengShouLuan: ZSL,
  DongRongLuan: DRL,
};

export {
  // eslint-disable-next-line import/prefer-default-export
  COL_CONIFGS,
  NUM_COL,
};
